import { Layout } from "@/components/layout/Layout";
import { motion } from "framer-motion";
import { Shape3DViewer } from "@/components/3d/Shape3DViewer";
import { ArrowLeft, RotateCcw, Grid3X3 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { useState } from "react";
import { Switch } from "@/components/ui/switch";

const shapes3D = [
  {
    id: "cube",
    name: "Cube",
    description: "A three-dimensional solid with six square faces, twelve edges, and eight vertices.",
    formula: "V = s³, SA = 6s²",
    properties: ["6 faces", "12 edges", "8 vertices"],
    color: "#8b5cf6",
  },
  {
    id: "sphere",
    name: "Sphere",
    description: "A perfectly round 3D shape where every point on the surface is equidistant from the center.",
    formula: "V = (4/3)πr³, SA = 4πr²",
    properties: ["No edges", "No vertices", "Infinite symmetry"],
    color: "#06b6d4",
  },
  {
    id: "cylinder",
    name: "Cylinder",
    description: "A solid with two parallel circular bases connected by a curved surface.",
    formula: "V = πr²h, SA = 2πr(r + h)",
    properties: ["2 circular faces", "1 curved surface", "2 edges"],
    color: "#ec4899",
  },
  {
    id: "cone",
    name: "Cone",
    description: "A solid with a circular base that tapers smoothly to a point called the apex.",
    formula: "V = (1/3)πr²h",
    properties: ["1 circular base", "1 apex", "1 curved surface"],
    color: "#10b981",
  },
  {
    id: "torus",
    name: "Torus",
    description: "A doughnut-shaped surface generated by rotating a circle around an axis.",
    formula: "V = 2π²Rr²",
    properties: ["No edges", "Genus 1", "Ring shape"],
    color: "#8b5cf6",
  },
  {
    id: "torusknot",
    name: "Torus Knot",
    description: "A mathematical knot that lies on the surface of a torus, creating intricate patterns.",
    formula: "Complex parametric",
    properties: ["Continuous curve", "Knotted", "Self-intersecting"],
    color: "#f59e0b",
  },
  {
    id: "tetrahedron",
    name: "Tetrahedron",
    description: "The simplest Platonic solid with four triangular faces, four vertices, and six edges.",
    formula: "V = (a³√2)/12",
    properties: ["4 faces", "6 edges", "4 vertices"],
    color: "#06b6d4",
  },
  {
    id: "octahedron",
    name: "Octahedron",
    description: "A Platonic solid with eight equilateral triangular faces, like two pyramids joined at their bases.",
    formula: "V = (√2/3)a³",
    properties: ["8 faces", "12 edges", "6 vertices"],
    color: "#ec4899",
  },
  {
    id: "dodecahedron",
    name: "Dodecahedron",
    description: "A Platonic solid with twelve regular pentagonal faces.",
    formula: "V = (15 + 7√5)/4 × a³",
    properties: ["12 faces", "30 edges", "20 vertices"],
    color: "#10b981",
  },
  {
    id: "icosahedron",
    name: "Icosahedron",
    description: "A Platonic solid with twenty equilateral triangular faces, appearing nearly spherical.",
    formula: "V = (5(3 + √5)/12) × a³",
    properties: ["20 faces", "30 edges", "12 vertices"],
    color: "#8b5cf6",
  },
  {
    id: "capsule",
    name: "Capsule",
    description: "A cylinder with hemispherical ends, commonly used in physics simulations.",
    formula: "V = πr²(h + 4r/3)",
    properties: ["2 hemispheres", "1 cylinder", "Smooth surface"],
    color: "#f59e0b",
  },
  {
    id: "pyramid",
    name: "Pyramid",
    description: "A polyhedron with a polygonal base and triangular faces meeting at a common apex.",
    formula: "V = (1/3) × base × h",
    properties: ["1 square base", "4 triangular faces", "5 vertices"],
    color: "#06b6d4",
  },
  {
    id: "prism",
    name: "Hexagonal Prism",
    description: "A prism with hexagonal bases, featuring six rectangular lateral faces.",
    formula: "V = (3√3/2)s²h",
    properties: ["2 hexagonal bases", "6 rectangular faces", "12 vertices"],
    color: "#ec4899",
  },
  {
    id: "ring",
    name: "Ring",
    description: "A flat circular shape with a hole in the center, also called an annulus in 3D.",
    formula: "A = π(R² - r²)",
    properties: ["Flat surface", "Circular hole", "2D in 3D space"],
    color: "#10b981",
  },
];

const container = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: { staggerChildren: 0.05 },
  },
};

const item = {
  hidden: { opacity: 0, scale: 0.8 },
  show: { opacity: 1, scale: 1 },
};

const Shapes3D = () => {
  const [selectedShape, setSelectedShape] = useState(shapes3D[0]);
  const [wireframe, setWireframe] = useState(false);

  return (
    <Layout>
      <div className="container mx-auto px-6 py-12">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-12"
        >
          <Link to="/shapes-2d" className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground mb-6 transition-colors">
            <ArrowLeft className="w-4 h-4" />
            Back to 2D Shapes
          </Link>
          
          <h1 className="text-4xl md:text-5xl font-display font-bold mb-4">
            3D <span className="gradient-text">Shapes</span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl">
            Explore interactive 3D models - rotate, zoom, and examine every angle.
          </p>
        </motion.div>

        {/* Controls */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="flex items-center gap-6 mb-8"
        >
          <div className="flex items-center gap-3">
            <Grid3X3 className="w-5 h-5 text-muted-foreground" />
            <span className="text-sm font-medium">Wireframe</span>
            <Switch checked={wireframe} onCheckedChange={setWireframe} />
          </div>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <RotateCcw className="w-4 h-4" />
            <span>Drag to rotate • Scroll to zoom</span>
          </div>
        </motion.div>

        {/* Main 3D View */}
        <motion.div
          key={selectedShape.id + wireframe}
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-card rounded-3xl border border-border p-8 mb-12"
        >
          <div className="grid lg:grid-cols-2 gap-8 items-center">
            <div className="aspect-square max-h-[400px]">
              <Shape3DViewer
                shape={selectedShape.id}
                color={selectedShape.color}
                wireframe={wireframe}
              />
            </div>

            <div>
              <h2 className="text-3xl font-display font-bold mb-4">
                {selectedShape.name}
              </h2>
              <p className="text-lg text-muted-foreground mb-6">
                {selectedShape.description}
              </p>
              
              <div className="space-y-4">
                <div className="p-4 bg-primary/5 rounded-xl border border-primary/20">
                  <span className="text-sm text-muted-foreground">Formula</span>
                  <p className="text-lg font-mono font-semibold text-primary mt-1">
                    {selectedShape.formula}
                  </p>
                </div>
                <div className="p-4 bg-secondary/5 rounded-xl border border-secondary/20">
                  <span className="text-sm text-muted-foreground">Properties</span>
                  <div className="flex flex-wrap gap-2 mt-2">
                    {selectedShape.properties.map((prop, i) => (
                      <span key={i} className="text-sm px-3 py-1 bg-secondary/20 rounded-full text-secondary">
                        {prop}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Shape Grid */}
        <motion.div
          variants={container}
          initial="hidden"
          animate="show"
          className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-7 gap-4"
        >
          {shapes3D.map((shape) => (
            <motion.button
              key={shape.id}
              variants={item}
              onClick={() => setSelectedShape(shape)}
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              className={`aspect-square p-3 rounded-2xl border transition-all flex flex-col items-center justify-center gap-2 ${
                selectedShape.id === shape.id
                  ? "bg-primary/10 border-primary"
                  : "bg-card border-border hover:border-primary/50"
              }`}
            >
              <div 
                className="w-10 h-10 rounded-xl flex items-center justify-center text-white text-xl font-bold"
                style={{ backgroundColor: shape.color }}
              >
                {shape.name[0]}
              </div>
              <span className="text-xs font-medium truncate max-w-full">
                {shape.name}
              </span>
            </motion.button>
          ))}
        </motion.div>

        {/* Navigation */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
          className="flex justify-between mt-12"
        >
          <Link to="/shapes-2d">
            <Button variant="outline" className="gap-2">
              <ArrowLeft className="w-4 h-4" />
              2D Shapes
            </Button>
          </Link>
          <Link to="/">
            <Button className="gap-2 gradient-bg">
              Back to Home
            </Button>
          </Link>
        </motion.div>
      </div>
    </Layout>
  );
};

export default Shapes3D;
