import { Layout } from "@/components/layout/Layout";
import { motion } from "framer-motion";
import { ArrowLeft, RotateCcw, Grid3X3, Box, Hexagon, Triangle, Circle, Pentagon, Octagon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { useState } from "react";

const shapes3D = [
  {
    id: "cube",
    name: "Cube",
    description: "A three-dimensional solid with six square faces, twelve edges, and eight vertices.",
    formula: "V = s³, SA = 6s²",
    properties: ["6 faces", "12 edges", "8 vertices"],
    color: "#8b5cf6",
    icon: Box,
  },
  {
    id: "sphere",
    name: "Sphere",
    description: "A perfectly round 3D shape where every point on the surface is equidistant from the center.",
    formula: "V = (4/3)πr³, SA = 4πr²",
    properties: ["No edges", "No vertices", "Infinite symmetry"],
    color: "#06b6d4",
    icon: Circle,
  },
  {
    id: "cylinder",
    name: "Cylinder",
    description: "A solid with two parallel circular bases connected by a curved surface.",
    formula: "V = πr²h, SA = 2πr(r + h)",
    properties: ["2 circular faces", "1 curved surface", "2 edges"],
    color: "#ec4899",
    icon: Circle,
  },
  {
    id: "cone",
    name: "Cone",
    description: "A solid with a circular base that tapers smoothly to a point called the apex.",
    formula: "V = (1/3)πr²h",
    properties: ["1 circular base", "1 apex", "1 curved surface"],
    color: "#10b981",
    icon: Triangle,
  },
  {
    id: "torus",
    name: "Torus",
    description: "A doughnut-shaped surface generated by rotating a circle around an axis.",
    formula: "V = 2π²Rr²",
    properties: ["No edges", "Genus 1", "Ring shape"],
    color: "#8b5cf6",
    icon: Circle,
  },
  {
    id: "tetrahedron",
    name: "Tetrahedron",
    description: "The simplest Platonic solid with four triangular faces, four vertices, and six edges.",
    formula: "V = (a³√2)/12",
    properties: ["4 faces", "6 edges", "4 vertices"],
    color: "#06b6d4",
    icon: Triangle,
  },
  {
    id: "octahedron",
    name: "Octahedron",
    description: "A Platonic solid with eight equilateral triangular faces, like two pyramids joined at their bases.",
    formula: "V = (√2/3)a³",
    properties: ["8 faces", "12 edges", "6 vertices"],
    color: "#ec4899",
    icon: Octagon,
  },
  {
    id: "dodecahedron",
    name: "Dodecahedron",
    description: "A Platonic solid with twelve regular pentagonal faces.",
    formula: "V = (15 + 7√5)/4 × a³",
    properties: ["12 faces", "30 edges", "20 vertices"],
    color: "#10b981",
    icon: Pentagon,
  },
  {
    id: "icosahedron",
    name: "Icosahedron",
    description: "A Platonic solid with twenty equilateral triangular faces, appearing nearly spherical.",
    formula: "V = (5(3 + √5)/12) × a³",
    properties: ["20 faces", "30 edges", "12 vertices"],
    color: "#8b5cf6",
    icon: Hexagon,
  },
  {
    id: "pyramid",
    name: "Pyramid",
    description: "A polyhedron with a polygonal base and triangular faces meeting at a common apex.",
    formula: "V = (1/3) × base × h",
    properties: ["1 square base", "4 triangular faces", "5 vertices"],
    color: "#06b6d4",
    icon: Triangle,
  },
  {
    id: "prism",
    name: "Hexagonal Prism",
    description: "A prism with hexagonal bases, featuring six rectangular lateral faces.",
    formula: "V = (3√3/2)s²h",
    properties: ["2 hexagonal bases", "6 rectangular faces", "12 vertices"],
    color: "#ec4899",
    icon: Hexagon,
  },
  {
    id: "capsule",
    name: "Capsule",
    description: "A cylinder with hemispherical ends, commonly used in physics simulations.",
    formula: "V = πr²(h + 4r/3)",
    properties: ["2 hemispheres", "1 cylinder", "Smooth surface"],
    color: "#f59e0b",
    icon: Circle,
  },
];

const container = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: { staggerChildren: 0.05 },
  },
};

const item = {
  hidden: { opacity: 0, scale: 0.8 },
  show: { opacity: 1, scale: 1 },
};

// Animated 3D shape preview using CSS
function Shape3DPreview({ shape, color }: { shape: string; color: string }) {
  return (
    <div className="w-full h-[300px] rounded-2xl overflow-hidden bg-muted/30 flex items-center justify-center">
      <motion.div
        className="relative"
        animate={{ rotateY: 360 }}
        transition={{ duration: 8, repeat: Infinity, ease: "linear" }}
        style={{ transformStyle: "preserve-3d", perspective: 800 }}
      >
        <div 
          className="w-32 h-32 rounded-2xl flex items-center justify-center"
          style={{ 
            background: `linear-gradient(135deg, ${color}, ${color}88)`,
            boxShadow: `0 20px 60px ${color}40`
          }}
        >
          <span className="text-6xl text-white font-bold opacity-80">{shape[0]}</span>
        </div>
        <motion.div 
          className="absolute inset-0 rounded-2xl border-2 opacity-30"
          style={{ borderColor: color }}
          animate={{ rotate: -360 }}
          transition={{ duration: 12, repeat: Infinity, ease: "linear" }}
        />
      </motion.div>
    </div>
  );
}

const Shapes3D = () => {
  const [selectedShape, setSelectedShape] = useState(shapes3D[0]);

  return (
    <Layout>
      <div className="container mx-auto px-6 py-12">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-12"
        >
          <Link to="/shapes-2d" className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground mb-6 transition-colors">
            <ArrowLeft className="w-4 h-4" />
            Back to 2D Shapes
          </Link>
          
          <h1 className="text-4xl md:text-5xl font-display font-bold mb-4">
            3D <span className="gradient-text">Shapes</span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl">
            Explore the fascinating world of three-dimensional geometry.
          </p>
        </motion.div>

        {/* Controls hint */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="flex items-center gap-6 mb-8"
        >
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <RotateCcw className="w-4 h-4" />
            <span>Animated 3D preview • Click to explore each shape</span>
          </div>
        </motion.div>

        {/* Main View */}
        <motion.div
          key={selectedShape.id}
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-card rounded-3xl border border-border p-8 mb-12"
        >
          <div className="grid lg:grid-cols-2 gap-8 items-center">
            <div className="aspect-square max-h-[400px]">
              <Shape3DPreview shape={selectedShape.name} color={selectedShape.color} />
            </div>

            <div>
              <div className="flex items-center gap-3 mb-4">
                <div 
                  className="w-12 h-12 rounded-xl flex items-center justify-center"
                  style={{ backgroundColor: selectedShape.color }}
                >
                  <selectedShape.icon className="w-6 h-6 text-white" />
                </div>
                <h2 className="text-3xl font-display font-bold">
                  {selectedShape.name}
                </h2>
              </div>
              <p className="text-lg text-muted-foreground mb-6">
                {selectedShape.description}
              </p>
              
              <div className="space-y-4">
                <div className="p-4 bg-primary/5 rounded-xl border border-primary/20">
                  <span className="text-sm text-muted-foreground">Formula</span>
                  <p className="text-lg font-mono font-semibold text-primary mt-1">
                    {selectedShape.formula}
                  </p>
                </div>
                <div className="p-4 bg-secondary/5 rounded-xl border border-secondary/20">
                  <span className="text-sm text-muted-foreground">Properties</span>
                  <div className="flex flex-wrap gap-2 mt-2">
                    {selectedShape.properties.map((prop, i) => (
                      <span key={i} className="text-sm px-3 py-1 bg-secondary/20 rounded-full text-secondary">
                        {prop}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Shape Grid */}
        <motion.div
          variants={container}
          initial="hidden"
          animate="show"
          className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4"
        >
          {shapes3D.map((shape) => (
            <motion.button
              key={shape.id}
              variants={item}
              onClick={() => setSelectedShape(shape)}
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              className={`aspect-square p-4 rounded-2xl border transition-all flex flex-col items-center justify-center gap-3 ${
                selectedShape.id === shape.id
                  ? "bg-primary/10 border-primary"
                  : "bg-card border-border hover:border-primary/50"
              }`}
            >
              <div 
                className="w-12 h-12 rounded-xl flex items-center justify-center text-white"
                style={{ backgroundColor: shape.color }}
              >
                <shape.icon className="w-6 h-6" />
              </div>
              <span className="text-sm font-medium truncate max-w-full">
                {shape.name}
              </span>
            </motion.button>
          ))}
        </motion.div>

        {/* Navigation */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
          className="flex justify-between mt-12"
        >
          <Link to="/shapes-2d">
            <Button variant="outline" className="gap-2">
              <ArrowLeft className="w-4 h-4" />
              2D Shapes
            </Button>
          </Link>
          <Link to="/">
            <Button className="gap-2 gradient-bg">
              Back to Home
            </Button>
          </Link>
        </motion.div>
      </div>
    </Layout>
  );
};

export default Shapes3D;
